name: Build and Deploy K8s

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: raf555/actions/.github/workflows/build-ghcr.yaml@v1
    permissions:
      contents: read
      packages: write
    with:
      image_name: "panel-stitch"
      tag: ${{ github.ref_name }}
    secrets: inherit

  deploy:
    needs: build
    uses: raf555/actions/.github/workflows/deploy.yaml@v1
    permissions:
      contents: read
    with:
      image_name: panel-stitch
      tag: ${{ github.ref_name }}
      path: 'apps/panel-stitch'
    secrets: inherit
