name: Cleanup old package versions

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: "panel-stitch"
          package-type: "container"
          min-versions-to-keep: 1
          delete-only-untagged-versions: false
